name: ddgr
summary: DuckDuckGo from the terminal
description: |
  ddgr is a cmdline utility to search DuckDuckGo from the terminal. While 
  googler is highly popular among cmdline users, in many forums the need 
  of a similar utility for privacy-aware DuckDuckGo came up. DuckDuckGo 
  Bangs are super-cool too! So here's ddgr for you!
  Unlike the web interface, you can specify the number of search results 
  you would like to see per page. It's more convenient than skimming through 
  30-odd search results per page. The default interface is carefully designed 
  to use minimum space without sacrificing readability.
  ddgr isn't affiliated to DuckDuckGo in any way..
  
  **Authors**

  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or officially maintained by the upstream developers.  

website: https://github.com/jarun/ddgr
contact: https://github.com/snapcrafters/ddgr/issues
issues: https://github.com/snapcrafters/ddgr/issues
source-code: https://github.com//snapcrafters/ddgr
license: MIT
icon: snap/local/ddg-logo.png
version: 'v2.1'

base: core22
grade: stable
confinement: strict

apps:
  ddgr:
    environment:
      LC_ALL: "C.UTF-8"
    command: usr/local/bin/ddgr
    plugs:
      - network
      - desktop

parts:
  ddgr:
    plugin: make
    source: https://github.com/jarun/ddgr.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    stage-packages:
      - python3
      - python3-requests
    prime:
      - -usr/bin/pdb3*
      - -usr/bin/dh_*
      - -usr/share/debhelper
      - -usr/share/dh-python
      - -usr/share/perl5/Debian
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian/overrides
      - -usr/share/man
      - -share/man
      - -usr/share/applications
      - -usr/share/pixmaps
      - -usr/bin/2to3*
      - -usr/lib/python*/lib2to3
      - -usr/lib/python*/idlelib
      - -usr/lib/python*/tkinter
      - -lib/python*/site-packages/pip
      - -lib/python*/site-packages/setuptools*
      - -lib/python*/site-packages/tests
      - -usr/lib/python*/venv
      - -lib/python*/site-packages/wheel*
      - -usr/share/X11/XErrorDB
 
  config:
    plugin: dump
    source: snap/local      
